[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = false

[[redirects]]
  from = "https://enterportal.org/*"
  to = "https://www.enterportal.org/:splat"
  status = 301
  force = true
